### ISSUE TITLE
&#65279

### ISSUE THREAD

**Issue by ch1y0q** [vc12345679/KaTeX4Typecho#1]
使用主题：casper

<body class="home-template nav-closed">
下一行生成"&#65279";
禁用插件后即正常。

**Comment by vc12345679** [comment]
我已经不用typecho了，能给个demo看看吗？

**Comment by ch1y0q** [comment]
* [禁用](http://web.archive.org/web/20170408140552/http://qwerty250.azurewebsites.net/)
* [启用](https://web.archive.org/web/20170408140712/http://qwerty250.azurewebsites.net/)

**Comment by vc12345679** [comment]
差别在什么地方？

**Comment by ch1y0q** [comment]
启用插件后顶部有空白条
查看html源码，白条实际是"&#65279";

**Comment by vc12345679** [comment]
哦，是BOM问题，多谢提醒！
已经处理好了，更新一下试试。

**Comment by ch1y0q** [comment]
Thanks!已解决。

**Comment by vc12345679** [comment]
my pleasure
