### ISSUE TITLE
某些情况下 \sum 、\leq、\cdot等无法解析

### ISSUE THREAD

**Issue by nolongerwait** [vc12345679/KaTeX4Typecho#2]
具体情况见http://nolongerwait.com/index.php/archives/16/
所以公式内涉及\xxx的均渲染失败。

**Comment by vc12345679** [comment]
equations in standalone mode should be included in the delimiters of `\\[ ... \\]` by default

**Comment by vc12345679** [comment]
Typecho是在服务器端用php对markdown进行渲染的，而这个插件是在浏览器端利用js对公式进行渲染；前者可能会误把公式代码进行markdown渲染，从而影响公式的正常显示。

Typecho renders MARKDOWN content in the server end (PHP), while this plug-in, renders equations in the browser end (JavaScript). 
On certain occasions, problems may occur if Typecho renders the code of equations in the server end by mistake.

权宜之计是用任意的html标签把公式代码包装一下，比如`<tex> ... </tex>`这样，请见[示例](https://blog.chensiwei.space/blog/texingitblog.html)

The temporary  solution is wrapping the content of equations by any HTML labels, such as, `<tex> ... </tex>`, except the ones in **ignored labels list** in the configurations.
You may find a demo [here](https://blog.chensiwei.space/blog/texingitblog.html).

**Comment by nolongerwait** [comment]
好的。谢谢指导！我去尝试修改一下。
